config/routes.rb
Rails.application.routes.draw do
  get 'esbuild', to: 'esbuild#index'
  get 'importmap', to: 'importmap#index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/esbuild_controller.rb
class EsbuildController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/importmap_controller.rb
class ImportmapController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/esbuild_helper.rb
module EsbuildHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/importmap_helper.rb
module ImportmapHelper
end

app/views/esbuild/index.html.erb
<div>
  <h1 class="font-bold text-4xl mb-4">Counter by React (builded by esbuild)</h1>
  <div id="esbuild-react">
</div>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
  <ul>
    <li><%= link_to "React and esbuild", esbuild_path %></li>
    <li><%= link_to "Stimulus and importmap", importmap_path %></li>
    <li></li>
  </ul>
</div>

app/views/importmap/index.html.erb
<div data-controller="importmap">
  <h1 class="font-bold text-4xl mb-4">Counter by Stimulus</h1>
  <input data-importmap-target="counter" type="text" value="0" class="block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 mb-3">
  <button data-action="click->importmap#increment" class="rounded bg-white px-3 text-lg font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 w-16">+1</button>
  <button data-action="click->importmap#decrement" class="rounded bg-white px-3 text-lg font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 w-16">-1</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportmapAndEsbuildSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag "builds/application" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>